#!/usr/bin/env bash
set -euo pipefail
CXX=${CXX:-g++}
CXXFLAGS='-O3 -std=c++17'
for src in \
  NO19_CASE_II_DD.cpp \
  NO19_CASE_II_DQ.cpp \
  NO19_CASE_I_PP.cpp \
  NO19_CASE_I_PQ_PSING_QANY.cpp \
  NO19_CASE_I_PQ_PPERM_QSING.cpp \
  NO19_CASE_O_PP.cpp \
  NO19_CASE_O_PQ_PSING_QANY.cpp \
  NO19_CASE_O_PQ_PPERM_QSING.cpp; do
  exe="${src%.cpp}.bin"
  "$CXX" $CXXFLAGS "$src" -o "$exe"
  echo "=== $src ==="
  "./$exe"
done
python3 NO19_EXACT9_WITNESS_CHECK.py
python3 NO19_DIRECT_WORD_AUDIT.py
python3 NO19_AFFINE_BASIS_CROSSCHECK.py
"$CXX" $CXXFLAGS NO19_UNARY_SAFE_ENUMERATOR.cpp -o NO19_UNARY_SAFE_ENUMERATOR.bin
./NO19_UNARY_SAFE_ENUMERATOR.bin
"$CXX" $CXXFLAGS NO19_UNARY_COUNTS_INDEPENDENT_V2.cpp -o NO19_UNARY_COUNTS_INDEPENDENT_V2.bin
./NO19_UNARY_COUNTS_INDEPENDENT_V2.bin

"$CXX" $CXXFLAGS NO19_SINGULAR_COUNTS_THIRD_BRUTE.cpp -o NO19_SINGULAR_COUNTS_THIRD_BRUTE.bin
./NO19_SINGULAR_COUNTS_THIRD_BRUTE.bin
"$CXX" $CXXFLAGS NO19_II_DD_ORBIT_AUDIT_INDEPENDENT.cpp -o NO19_II_DD_ORBIT_AUDIT_INDEPENDENT.bin
./NO19_II_DD_ORBIT_AUDIT_INDEPENDENT.bin
python3 NO19_LOCAL_SURVIVOR_CROSSBRANCH_SPOTCHECK.py
